services:
  kong:
    image: kong:3.9.1

    command: kong start

    networks:
      - chat-net
    depends_on:
      - server
    ports:
      - ${SERVER_PORT}:8000
      - ${API_GATEWAY_ADMIN_PORT}:8001

    volumes:
      - ./kong/kong.conf:/etc/kong/kong.conf
