name: Vite Build

on:
  workflow_dispatch: # 수동으로 실행 가능
  pull_request: # PR이 열릴 때마다 실행
    branches:
      - main

permissions:
  contents: write # 레포지토리 콘텐츠에 대한 쓰기 권한
  actions: read # 액션에 대한 읽기 권한
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VITE_MF_TYPE: ${{ vars.VITE_MF_TYPE }}
      VITE_LAYOUT_WIDTH: ${{ vars.VITE_LAYOUT_WIDTH }}
      VITE_LAYOUT_HEIGHT: ${{ vars.VITE_LAYOUT_HEIGHT }}
      VITE_SOCKET_SERVER_URL: ${{ vars.VITE_SOCKET_SERVER_URL }}
      VITE_SOCKET_ON_SYSTEM: ${{ vars.VITE_SOCKET_ON_SYSTEM }}
      VITE_SOCKET_ON_MESSAGE: ${{ vars.VITE_SOCKET_ON_MESSAGE }}
      VITE_SOCKET_ON_ROOM_CREATED: ${{ vars.VITE_SOCKET_ON_ROOM_CREATED }}
      VITE_SOCKET_ON_TYPING: ${{ vars.VITE_SOCKET_ON_TYPING }}
      VITE_SOCKET_EMIT_REGISTER: ${{ vars.VITE_SOCKET_EMIT_REGISTER }}
      VITE_SOCKET_EMIT_MESSAGE: ${{ vars.VITE_SOCKET_EMIT_MESSAGE }}
      VITE_SOCKET_EMIT_CREATE_ROOM: ${{ vars.VITE_SOCKET_EMIT_CREATE_ROOM }}
      VITE_SOCKET_EMIT_LEAVE_ROOM: ${{ vars.VITE_SOCKET_EMIT_LEAVE_ROOM }}
      VITE_SOCKET_EMIT_INVITE_ROOM: ${{ vars.VITE_SOCKET_EMIT_INVITE_ROOM }}
      VITE_SOCKET_EMIT_TYPING: ${{ vars.VITE_SOCKET_EMIT_TYPING }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci # 의존성 설치

      - name: Run tests
        run: npm run test:coverage # 테스트 실행

      - name: Lint code
        run: npm run lint # 린트 실행

      - name: Build Vite project
        env:
          VITE_PUBLIC_URL: ${{ vars.VITE_GH_PAGE_URL }}
          VITE_STANDALONE: true
          VITE_AUTH_PARCEL_URL: ${{ vars.VITE_GH_PAGE_AUTH_PARCEL_URL }}
          VITE_MANUAL_USER_SET: ${{ vars.VITE_GH_PAGE_MANUAL_USER_SET }}
        run: |
          npm run build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # 아티팩트를 업로드하는 액션
        with:
          name: build-artifact # 아티팩트 이름
          path: dist
